version: '3'

services:
  spotify:
    build:
      context: .
    container_name: spotify
    image: audiostation/spotify:v1.0
    network_mode: "host"
    volumes:
      - /tmp/sharesound:/tmp/sharesound
